project_id = "jwflhzyqcmwmehnhvbwf"

[functions.orders-api]
verify_jwt = false

[functions.create-admin]
verify_jwt = true

[functions.push-subscribe]
verify_jwt = false

[functions.send-notification]
verify_jwt = true

[functions.forward-order-to-hub]
verify_jwt = true

[functions.check-hub-order-status]
verify_jwt = true
